// apps/teleparty-spacetime/src/components/stage-cursor.tsx
type StageCursorProps = Readonly<{
  color: string
  displayName: string
  isSelf?: boolean
  x: number
  y: number
}>

export function StageCursor({
  color,
  displayName,
  isSelf = false,
  x,
  y,
}: StageCursorProps) {
  return (
    <div
      className="pointer-events-none absolute"
      style={{
        left: `${x.toFixed(3)}%`,
        top: `${y.toFixed(3)}%`,
        zIndex: isSelf ? 20 : 10,
      }}
    >
      <div className="relative -translate-x-1/2 -translate-y-1/2">
        <div
          className={isSelf ? 'scale-110' : undefined}
          style={{
            filter: 'drop-shadow(0 6px 12px rgba(15, 23, 42, 0.28))',
          }}
        >
          <svg
            aria-hidden="true"
            className="h-6 w-6"
            viewBox="0 0 24 24"
            fill="none"
          >
            <path
              d="M6.9 3.2C5.7 3.2 4.9 4 4.7 5.1L3.55 16.8C3.45 18.1 4.5 19.05 5.76 18.75L10.9 17.5C11.48 17.36 12.08 17.58 12.44 18.05L13.46 19.37C14.3 20.44 16 19.93 16.12 18.58L16.62 13.3C16.68 12.63 17.08 12.04 17.68 11.73L19.2 10.95C20.7 10.18 20.72 8.05 19.24 7.24L8.84 3.58C8.22 3.32 7.56 3.2 6.9 3.2Z"
              fill={color}
              stroke="rgba(255,255,255,0.9)"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="1.15"
            />
            <path
              d="M12.55 9.1C13.58 8.42 14.95 8.96 15.2 10.17C15.42 11.23 14.72 12.3 13.64 12.5C12.54 12.7 11.55 11.82 11.6 10.7C11.62 10.02 11.96 9.5 12.55 9.1Z"
              fill="rgba(255,255,255,0.22)"
              stroke="rgba(255,255,255,0.52)"
              strokeWidth="0.8"
            />
          </svg>
        </div>
        <div className="absolute left-4 top-4 flex items-center gap-1.5 rounded-full border border-white/55 bg-slate-950/72 px-2.5 py-1 text-[10px] font-semibold text-white shadow-lg shadow-slate-950/25 backdrop-blur-md">
          <span
            aria-hidden="true"
            className="size-2 rounded-full border border-white/70"
            style={{ backgroundColor: color }}
          />
          <span className="max-w-28 truncate">{displayName}</span>
          {isSelf ? <span className="text-[9px] text-white/70">you</span> : null}
        </div>
      </div>
    </div>
  )
}

// apps/teleparty-sveltekit/src/lib/components/StageCursor.svelte
<script lang="ts">
	type CursorViewModel = {
		color: string;
		displayName: string;
		isSelf?: boolean;
		x: number;
		y: number;
	};

	let { color, displayName, isSelf = false, x, y }: CursorViewModel = $props();
</script>

<div class="cursor-shell" style={`left: ${x}%; top: ${y}%; z-index: ${isSelf ? 30 : 20};`}>
	<div class:solo={isSelf} class="cursor-chip" style={`--cursor-color: ${color};`}>
		<span class="cursor-glyph" aria-hidden="true">
			<svg viewBox="0 0 28 28" fill="none">
				<defs>
					<mask id="rounded-pointer-mask">
						<rect width="28" height="28" fill="black"></rect>
						<path
							d="M10.2 4.2C11.5 3.5 13.1 3.6 14.3 4.5L21.1 10C22.4 11 22.8 12.7 22.2 14.2L17.8 23C17 24.6 15.1 25.4 13.5 24.8L6.4 21.8C4.7 21.1 3.7 19.3 3.9 17.5L5.1 8.7C5.3 7.1 6.2 5.7 7.5 5L10.2 4.2Z"
							fill="white"
						></path>
						<circle cx="10.4" cy="15.6" r="3.2" fill="black"></circle>
					</mask>
				</defs>
				<path
					d="M10.2 4.2C11.5 3.5 13.1 3.6 14.3 4.5L21.1 10C22.4 11 22.8 12.7 22.2 14.2L17.8 23C17 24.6 15.1 25.4 13.5 24.8L6.4 21.8C4.7 21.1 3.7 19.3 3.9 17.5L5.1 8.7C5.3 7.1 6.2 5.7 7.5 5L10.2 4.2Z"
					fill={color}
					mask="url(#rounded-pointer-mask)"
					stroke="rgba(255,255,255,0.92)"
					stroke-linecap="round"
					stroke-linejoin="round"
					stroke-width="1.2"
				></path>
				<path
					d="M14.2 8.4C15.3 7.9 16.6 8.3 17.2 9.2C17.8 10.2 17.5 11.5 16.5 12.2C15.4 12.9 14 12.6 13.3 11.6C12.6 10.4 12.9 9 14.2 8.4Z"
					fill="rgba(255,255,255,0.3)"
					stroke="rgba(255,255,255,0.45)"
					stroke-width="0.75"
				></path>
			</svg>
		</span>
		<span class="cursor-name">{displayName}</span>
		{#if isSelf}
			<span class="cursor-self">you</span>
		{/if}
	</div>
</div>

<style>
	.cursor-shell {
		position: absolute;
		pointer-events: none;
		transform: translate(-50%, -50%);
	}

	.cursor-chip {
		display: inline-flex;
		align-items: center;
		gap: 0.5rem;
		border-radius: 999px;
		border: 1px solid color-mix(in oklch, white 64%, var(--cursor-color) 36%);
		background:
			linear-gradient(135deg, color-mix(in oklch, white 92%, var(--cursor-color) 8%), color-mix(in oklch, white 82%, var(--cursor-color) 18%));
		padding: 0.28rem 0.7rem 0.28rem 0.38rem;
		box-shadow:
			0 14px 28px rgba(38, 26, 18, 0.18),
			0 2px 0 rgba(255, 255, 255, 0.5) inset;
		color: oklch(22% 0.03 34);
		font-size: 0.72rem;
		font-weight: 700;
		letter-spacing: 0.02em;
		backdrop-filter: blur(12px);
	}

	.cursor-chip.solo {
		transform: translateY(-2px);
	}

	.cursor-glyph {
		display: inline-flex;
		height: 1rem;
		width: 1rem;
		flex: none;
	}

	.cursor-glyph svg {
		display: block;
		height: 100%;
		width: 100%;
		filter: drop-shadow(0 4px 10px rgba(62, 37, 18, 0.18));
	}

	.cursor-name {
		max-width: 12ch;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.cursor-self {
		color: oklch(43% 0.08 20);
		font-size: 0.6rem;
		font-weight: 800;
		letter-spacing: 0.09em;
		text-transform: uppercase;
	}
</style>
