// apps/teleparty-sveltekit/src/lib/components/StageDrawing.svelte
<script lang="ts">
	import type { DrawingStroke, StagePoint } from '$lib/rooms';

	type PreviewStroke = {
		color: string;
		points: StagePoint[];
	} | null;

	let {
		strokes,
		previewStroke = null
	}: {
		strokes: DrawingStroke[];
		previewStroke?: PreviewStroke;
	} = $props();

	function toPointString(points: StagePoint[]): string {
		return points.map((point) => `${point.x * 100},${point.y * 100}`).join(' ');
	}
</script>

<svg aria-hidden="true" class="drawing-layer" viewBox="0 0 100 100" preserveAspectRatio="none">
	{#each strokes as stroke (stroke.strokeId)}
		<polyline
			fill="none"
			points={toPointString(stroke.points)}
			stroke="rgba(255, 255, 255, 0.7)"
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="2.4"
		/>
		<polyline
			fill="none"
			points={toPointString(stroke.points)}
			stroke={stroke.color}
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="1.45"
		/>
	{/each}

	{#if previewStroke}
		<polyline
			fill="none"
			points={toPointString(previewStroke.points)}
			stroke="rgba(255, 255, 255, 0.75)"
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="2.4"
			stroke-dasharray="0 0"
		/>
		<polyline
			fill="none"
			points={toPointString(previewStroke.points)}
			stroke={previewStroke.color}
			stroke-linecap="round"
			stroke-linejoin="round"
			stroke-width="1.45"
			stroke-dasharray="0 0"
		/>
	{/if}
</svg>

<style>
	.drawing-layer {
		position: absolute;
		inset: 0.65rem;
		height: calc(100% - 1.3rem);
		width: calc(100% - 1.3rem);
		pointer-events: none;
		overflow: visible;
	}
</style>

// apps/teleparty-spacetime/src/components/stage-drawing.tsx
type StagePoint = Readonly<{
  x: number
  y: number
}>

type StageStroke = Readonly<{
  color: string
  points: readonly StagePoint[]
  strokeId: string
}>

type StageDrawingProps = Readonly<{
  previewStroke?: Omit<StageStroke, 'strokeId'> | null
  strokes: readonly StageStroke[]
}>

function toPath(points: readonly StagePoint[]) {
  if (points.length === 0) {
    return ''
  }

  const [firstPoint, ...restPoints] = points
  if (!firstPoint) {
    return ''
  }

  return [
    `M ${firstPoint.x * 100} ${firstPoint.y * 100}`,
    ...restPoints.map((point) => `L ${point.x * 100} ${point.y * 100}`),
  ].join(' ')
}

export function StageDrawing({ previewStroke = null, strokes }: StageDrawingProps) {
  return (
    <svg
      aria-hidden="true"
      className="pointer-events-none absolute inset-2 h-[calc(100%-1rem)] w-[calc(100%-1rem)]"
      preserveAspectRatio="none"
      viewBox="0 0 100 100"
    >
      {strokes.map((stroke) => (
        <path
          key={stroke.strokeId}
          d={toPath(stroke.points)}
          fill="none"
          stroke={stroke.color}
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeOpacity="0.92"
          strokeWidth="0.85"
        />
      ))}
      {previewStroke ? (
        <path
          d={toPath(previewStroke.points)}
          fill="none"
          stroke={previewStroke.color}
          strokeDasharray="1.8 1.2"
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeOpacity="0.9"
          strokeWidth="0.9"
        />
      ) : null}
    </svg>
  )
}
